### PR TITLE
fix list style

### PR DESCRIPTION
**Pull request by xieyuheng**
specify `outside`, otherwise it would be `inside`.

### CODE REVIEW

**Comment by xieyuheng** [comment]
I also added utterances support in this PR,
sorry to do two things in one PR.

**Comment by kaiiiz** [comment]
@xieyuheng thanks for your contribution at first. `list-style: outside` is actually a good idea. But the circle kinda miss position like the screenshot below.
align
The default value of ul's `margin` in spectre.css is set to `.8rem 0 .8rem .8rem;`. However, I think override `margin-left: 1rem` will place all things in the right position.
What do you think?

**Comment by xieyuheng** [comment]
I tried `margin-left: 1rem;`,
below are how they look like:

**Comment by xieyuheng** [comment]
my page is at :: http://lang-study.surge.sh/review/do-it-yourself-type-theory
source of markdown files at :: https://github.com/xieyuheng/study
this is how they look like with `list-style: outside;`

**Comment by xieyuheng** [comment]
as lone as I can avoid the extra line break after the dot, it will be ok.

**Comment by xieyuheng** [comment]
Also the link :: https://kaiiiz.github.io/note/,
in "Another demo of this theme, visit my personal `note`." is broken.

**Comment by kaiiiz** [comment]
@xieyuheng Sorry for misleading. `list-style: outside;` is a good idea, I'll add it. What I'm concerned is that the circle on the left hand side.

After setting `list-style: outside;`, the circle will overflow to the left if follow the default value in spectre.css:

image

Setting `margin-left: 1rem` in `ul` to override the definition in spectre.css will look better.

image

As for the link, I'll remove it, thanks for reminding me. I totally forgot that.

**Comment by xieyuheng** [comment]
mis-understanding is my fault, thanks for explaining.
I made the change.

**Comment by kaiiiz** [comment]
LGTM, thanks for your contribution. :)

**Pull request merged**
